Ecommerce/Ecommerce/urls.py
# Uncomment next two lines to enable admin:
#from django.contrib import admin
#from django.urls import path

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/app1/urls.py
from django.urls import path
from .views import *
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('master/',master,name="master"),
    path('',home,name="home"), 

    path('register/',handle_register,name="register"), 
    path('register/SignupAuthentication/',signupAuthentication,name="SignupAuthentication"), 

    path('login/',handle_login,name="login"),
    path('logout/',handle_logout,name="logout"),
    path('forgot_password/',forgot_password,name="forgotpassword"),
    path('forgotOtp/',forgotOtp,name="forgotOtp"),
    path('newpassword/', newpassword,name='newpassword'),

    path('product/',product,name="product"), 
    path('add_to_wishlist/<int:pk>/',add_to_wishlist,name="add_to_wishlist"), 
    path('show_wishlist/',show_wishlist,name="showwishlist"), 
    path('delete_to_wishlist/<int:id>/',delete_to_wishlist,name="deletetowishlist"), 

    path('addtocart/<int:pk>/',add_to_cart,name="addtocart"),
    path('showmycart/',show_mycart,name="showmycart"),

    path('cart_update/<int:id>/',cart_update,name="cart_update"),
    path('cart_remove/<int:id>/',cart_remove,name="cart_remove"),
    path('deleteitem/<int:id>/',remove_items, name='deleteitem'),

    path('cart/checkout/',checkout,name="checkout"),       
    path('cart/checkout/success/',success,name="success"),

    path('tracking/',tracking,name="tracking"),    

    path('myaccount/',myaccount,name="myaccount"),    
         
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Ecommerce/app1/models.py
from enum import unique
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
import datetime
import uuid

# Create your models here.

class Signup(models.Model):
    firstname=models.CharField( max_length=50)
    lastname=models.CharField( max_length=50)
    email=models.EmailField(max_length=254)
    phone=models.IntegerField(default='')
    password=models.CharField(max_length=50)
    confirmpassword=models.CharField(max_length=50,default='')    

    def __str__(self):
        return self.firstname

class Categories(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Subcategories(models.Model):
    categories = models.ForeignKey(Categories,on_delete=models.CASCADE,default='')
    name = models.CharField(max_length=200,default='')

    def __str__(self):
        return self.name

class Filter_Price(models.Model):
    Filter_Price = (
        ('100 TO 500','100 TO 500'),  
        ('500 TO 1000','500 TO 1000'),  
        ('1000 TO 10000','1000 TO 10000'),  
        ('10000 TO 20000','10000 TO 20000'),
        ('20000 TO 30000','20000 TO 30000'),
        ('30000 TO 40000','30000 TO 40000'),
        ('40000 TO 50000','40000 TO 50000'),
        ('50000 TO 60000','50000 TO 60000'),
        ('60000 TO 70000','60000 TO 70000'),
        ('70000 TO 80000','70000 TO 80000'),               
    )
    price=models.CharField(choices=Filter_Price,max_length=60)

    def __str__(self):
        return self.price

class Product(models.Model):   
    CONDITION=(('New','New'),('Old','Old'))
    STOCK=(('IN STOCK','IN STOCK'),('OUT OF STOCK','OUT OF STOCK'))
    STATUS=(('PUBLISH','PUBLISH'),('DRAFT','DRAFT'))

    categories=models.ForeignKey(Categories,on_delete=models.CASCADE)
    subcategories=models.ForeignKey(Subcategories,on_delete=models.CASCADE)  
    unique_id=models.CharField(unique=True,max_length=200,null=True,blank=True)     
    name=models.CharField(max_length=200)
    price = models.FloatField()         
    total_stock=models.PositiveIntegerField()
    image=models.ImageField(upload_to='product-img/')    
    description=RichTextField(null=True)
    created_date=models.DateTimeField(default=timezone.now)    

    condition=models.CharField(choices=CONDITION,max_length=100)
    stock=models.CharField(choices=STOCK,max_length=200)
    status=models.CharField(choices=STATUS,max_length=200)
    filter_price=models.ForeignKey(Filter_Price,on_delete=models.CASCADE)

    def save(self, *args , **kwargs):
        if self.unique_id is None and self.created_date and self.id:
            self.unique_id = self.created_date.strftime('75%Y%m%d23') + str(self.id)
        return super().save(*args,**kwargs)

    # def __str__(self):
    #     return self.name

    # def category(self):
    #     return "\n".join([c.name for c in self.categories.all()])

class Wishlist(models.Model):
    user=models.ForeignKey(Signup,null=True,blank=True, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    
    def __str__(self):        
        return self.user.firstname

class Mycart(models.Model):
    user=models.ForeignKey(Signup,null=True,blank=True, on_delete=models.CASCADE)    
    product=models.ForeignKey(Product, on_delete=models.CASCADE) 
    quantity=models.PositiveIntegerField()   
    status=models.BooleanField(default=False)
    added_on = models.DateTimeField(auto_now_add=True,null=True)
    update_on= models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):        
        return self.user.firstname

Track = (
        ('Pending','Pending'),  
        ('Shipped','Shipped'),  
        ('Delivered','Delivered'),                         
    )
class Order(models.Model):
    unique_id= models.CharField(max_length=200,blank=False,null=False) 
    user=models.ForeignKey(Signup,on_delete=models.CASCADE)    
    firstname=models.CharField(max_length=100)
    lastname=models.CharField(max_length=100)
    country=models.CharField(max_length=100)
    address=models.TextField()
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    postcode=models.IntegerField()
    phone=models.IntegerField()
    email=models.EmailField(max_length=100)
    # description=models.TextField()
    amount=models.CharField(max_length=100)
    payment_id=models.CharField(max_length=300,null=True,blank=True)
    paid=models.BooleanField(default=False)
    date=models.DateTimeField(auto_now_add=True)
    track = models.CharField(choices=Track,default='Pending',max_length=200)

    def __str__(self):
        return self.user.firstname

class OrderItems(models.Model):
    user=models.ForeignKey(Signup,on_delete=models.CASCADE,null=True)
    order=models.ForeignKey(Order,on_delete=models.CASCADE)      
    product=models.CharField(max_length=200)
    image=models.ImageField(upload_to='media/Order_img')
    quantity=models.CharField(max_length=20)
    price=models.CharField(max_length=50)
    total=models.CharField(max_length=1000)

    def __str__(self):
        return self.order.user.firstname

Ecommerce/app1/views.py
from multiprocessing import context
from wsgiref.util import request_uri
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail
from app1.models import *
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
import razorpay
from django.views.decorators.csrf import csrf_exempt
import random

# Create your views here.
client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID,settings.RAZORPAY_KEY_SECRET))

def master(request):
    if request.session.has_key('email'):
        obj = Signup.objects.get(email=request.session['email'])
        all = Mycart.objects.filter(user_id=obj.id)
        l=[]                                     
        total=0
        for i in all:            
            l.append(i.product)              
            total=total + i.product.price                                 
        return render(request,'Master/master.html',{'al':l,'all':all,'total':total,'wishlist':wishlist})                            
    return render(request,'Master/master.html')    

def home(request):        
    if request.session.has_key('email'):
        obj = Signup.objects.get(email=request.session['email'])
        all = Mycart.objects.filter(user_id=obj.id)
        l=[]                                     
        total=0
        for i in all:            
            l.append(i.product)              
            total=total + i.product.price                           

        wishlist = Wishlist.objects.filter(user_id=obj.id)                         
        wish=[] 
        for i in wishlist:                       
            wish.append(i)

        categories = Categories.objects.all().order_by('name')    
    
        context = {
            'categories':categories,
            'al':l,
            'w':wish,
        }
        return render(request,'Master/home.html',context)  
    else:
        categories = Categories.objects.all().order_by('name') 
        context = {
            'categories':categories,                          
        }
    return render(request,'Master/home.html',context)    

sign=Signup()
def handle_register(request):
    if request.method=="POST":        
        sign.firstname=request.POST['firstname']
        sign.lastname=request.POST['lastname']
        sign.email=request.POST['email']
        sign.phone=request.POST['mobile']
        sign.password=request.POST['password']        
        sign.confirmpassword=request.POST['confirmpassword']        
       
        if Signup.objects.filter(email=sign.email).exists():            
            return JsonResponse({'opstatus':'Error'})
        else:                   
            otp = ''
            rand = random.choice('0123456789')
            rand1 = random.choice('0123456789')
            rand2 = random.choice('0123456789')
            rand3 = random.choice('0123456789')
            otp = rand + rand1 + rand2 + rand3 

            request.session['otp'] = otp                  
            subject = 'Email Verification'
            message = otp
            email_from= settings.EMAIL_HOST_USER
            recipient_list = [sign.email]
            send_mail( subject, message, email_from, recipient_list )                                             
            return JsonResponse({'opstatus':'Success'})
        
    return render(request,'Login/register.html')

def signupAuthentication(request):
    if request.session.has_key('otp'):
        otp = request.session['otp']        
        try:
            otpobj = request.POST.get('otp')                                  
            if otp == otpobj:
                sign.save()
                return redirect('login')                                                                
        except:            
            return redirect('SignupAuthentication')
    return render(request,'Login/SignupAuthentication.html')

def handle_login(request):
    if request.method=="POST":
        try:
            e=request.POST['email'] 
            request.session['email']=e            
            p=request.POST['password']                       
            x=Signup.objects.get(email=e)                         
            if x.password==p:
                # messages.success(request, f'you are now logged')
                return JsonResponse({'optstatus':'success'})
                # return redirect('home')
            else:
                messages.warning(request, 'Please input correct password')
                # return JsonResponse({'optstatus':'error'})
        except:
            messages.warning(request,'Enter Username And Password.')
    return render(request,'Login/login.html')

def forgot_password(request):         
    if request.method == 'POST':
        email = request.POST.get('email')
        request.session['forgot'] = email
        if Signup.objects.filter(email=email).exists():            
            otp = ''
            rand = random.choice('0123456789')
            rand1 = random.choice('0123456789')
            rand2 = random.choice('0123456789')
            rand3 = random.choice('0123456789')
            otp = rand + rand1 + rand2 + rand3                        
            request.session['otp'] = otp
                
            subject = 'Forgot Password'
            message = otp
            email_from= settings.EMAIL_HOST_USER
            recipient_list = [email]            
            send_mail( subject, message, email_from, recipient_list )
            return JsonResponse({'optstatus':'Success'})
        else:
            return JsonResponse({'opstatus':'Error'})   
    return render(request,'Login/forgot.html')

def forgotOtp(request):
    e = request.session['forgot']   
    if request.session.has_key('otp'):
        otp = request.session['otp'] 
        print(otp)             
        if request.method == 'POST':                                               
            if otp == request.POST.get('otp'):
                del request.session['otp']
                return JsonResponse({'optstatus':'Success'})
            else:
                return JsonResponse({'optstatus':'Wrong'})
    return render(request,'Login/forgotOtp.html')

def newpassword(request):
    if request.session.has_key('forgot'):
        e = request.session['forgot']             
        if request.method == "POST":                
            new_pass = request.POST.get('newpassword')   
            print(new_pass)                
            obj = Signup.objects.get(email = e)      
            print(obj.email)      
            obj.password = new_pass
            obj.confirmpassword = new_pass
            obj.save()
            del request.session['forgot']
            return JsonResponse({'optstatus':'Success'})
    else:
        return JsonResponse({'optstatus':'SecondTime'})
    return render(request,'Login/newpassword.html')    

def handle_logout(request):
    if request.session.has_key('email'):
        del request.session['email']
        return redirect('/')

def product(request):
    if request.session.has_key('email'):
        obj = Signup.objects.get(email=request.session['email'])
        all = Mycart.objects.filter(user_id=obj.id)
        l=[]                                     
        total=0
        for i in all:            
            l.append(i.product)              
            total=total + i.product.price 

        wishlist = Wishlist.objects.filter(user_id=obj.id)                         
        wish=[] 
        wish2=[]          
        for i in wishlist:                    
            wish.append(i)     
            wish2.append(i.product.pk)                                    

        categories = Categories.objects.all().order_by('name')    
        filter_price=Filter_Price.objects.all().order_by('price')

        categoryID=request.GET.get('subcategory')
        filterID=request.GET.get('filter_price')
        filterID=request.GET.get('filter_price')
        ATOZ_ID=request.GET.get('ATOZ')
        ZTOA_ID=request.GET.get('ZTOA')
        LowTOHigh_ID=request.GET.get('LowTOHigh')
        HightToLow_ID=request.GET.get('HightToLow')
        New_ID=request.GET.get('New')
        Old_ID=request.GET.get('Old')

        Search_Id=request.GET.get('search')

        if categoryID:
            product=Product.objects.filter( subcategories = categoryID , status = 'PUBLISH')            

        elif filterID:
            product=Product.objects.filter( filter_price = filterID , status = 'PUBLISH')
    
        elif ATOZ_ID:
            product=Product.objects.filter( status = 'PUBLISH' ).order_by('name')

        elif ZTOA_ID:
            product=Product.objects.filter( status = 'PUBLISH' ).order_by('-name')
        
        elif LowTOHigh_ID:
            product=Product.objects.filter( status = 'PUBLISH' ).order_by('price')

        elif HightToLow_ID:
            product=Product.objects.filter( status = 'PUBLISH' ).order_by('-price')

        elif New_ID:
            product=Product.objects.filter( status = 'PUBLISH',condition = 'New' )

        elif Old_ID:
            product=Product.objects.filter( status = 'PUBLISH',condition = 'Old' )        

        elif Search_Id:                                        
            product=Product.objects.filter( status = 'PUBLISH' , name__icontains=Search_Id) 
            if not product:                
                messages.warning(request, 'Search Not Found')                          

        else:
            product=Product.objects.filter( status = 'PUBLISH' ).order_by('-id') 
        
        context = {
            'categories':categories,
            'product':product,  
            'filter_price':filter_price,
            'al':l, 
            'w':wish,
            'w2':wish2,
        }
        return render(request,'Master/product.html',context)
    else:

Ecommerce/app1/templates/Master/home.html
{% extends 'Master/master.html' %}
{% load static %}

    {% block title %}        
      <title>Home</title>
      <link rel="stylesheet" href="{% static 'css/Master/home.css' %}">
    {% endblock %}

{% block content %}    

<div class="row mt-3">
    <div class="col-md-12 col-xs-12">
        <h4 class="text-center text-dark">All Categories</h4>        
    </div>
</div>
<div class="row mt-5 mb-5">
    {% for cat in categories %}
   <div class="col-md-4 col-xs-12">     
        <div class="card text-white mb-5" style="max-width: 18rem;">
            <div class="card-header text-center">{{ cat.name }}</div>
            <div class="card-body">    
            {% for i in cat.subcategories_set.all %}        
            <a href="/product/?subcategory={{ cat.id }}" class="text-dark">{{i.name}}<br></a>
            {% endfor %}            
            </div>
        </div>        
   </div> 
   {% endfor %}  
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'js/Master/home.js' %}"></script>
{% endblock %}

Ecommerce/app1/templates/Master/product.html
{% extends 'Master/master.html' %}
{% load static %}

{% block title %}        
      <title>Product</title>
      <link rel="stylesheet" href="{% static 'css/Master/product.css' %}">      
{% endblock %}

{% block content %}

<div class="row mt-3 mb-3 justify-content-between">
    <div class="col-md-5 col-xs-6">
        <form method="GET" class="form-inline my-2 my-lg-0">
            {% csrf_token %}
            <input class="form-control mr-sm-2 search" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn my-2 my-sm-0 BtnSearch" type="submit">Search</button>
        </form>
    </div>
    <div class="col-md-7 col-xs-6" style="text-align: right;margin: auto 0;">
        {% comment %} <div class="dropdown show text-right">
            <a class="btn btn-light filterbtn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Default
            </a>
          
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#">Name, A to Z</a>
              <a class="dropdown-item" href="#">Name, Z to A</a>
              <a class="dropdown-item" href="#">Price - High To Low</a>
              <a class="dropdown-item" href="#">Sort By new </a>              
              <a class="dropdown-item" href="#">Sort By old</a>                            
            </div>
        </div> {% endcomment %}
        {% comment %} <label for="selectbox1" style="display: inline-block;">Sort by:</label>
        <div class="drop-down">
            <div class="selected">
              <a href="#"><span>Please select</span></a>
            </div>
            <div class="options">
              <ul>
                <li><a href="#">Name, A to Z</a></li>
                <li><a href="#">Name, Z to A</a></li>
                <li><a href="#">Price - Low To High</a></li>
                <li><a href="#">Price - High To Low</a></li>
                <li><a href="#">Sort By new</a></li>
                <li><a href="#">Sort By old</a></li>
              </ul>
            </div>
        </div> {% endcomment %}
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" style="color:#323232;" type="button" id="dropdownMenuButton" class="DrpSortBy" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Default
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% for i in product%}/product/?ATOZ={{i.id}}{% endfor %}">Name, A to Z</a>
              <a class="dropdown-item" href="{% for i in product%}/product/?ZTOA={{i.id}}{% endfor %}">Name, Z to A</a>
              <a class="dropdown-item" href="{% for i in product%}/product/?LowTOHigh={{i.id}}{% endfor %}">Price - Low To High</a>
              <a class="dropdown-item" href="{% for i in product%}/product/?HightToLow={{i.id}}{% endfor %}">Price - High To Low</a>
              <a class="dropdown-item" href="{% for i in product%}/product/?New={{i.id}}{% endfor %}">Sort By new</a>
              <a class="dropdown-item" href="{% for i in product%}/product/?Old={{i.id}}{% endfor %}">Sort By old</a>

            </div>
          </div>
        {% comment %} <select id="selectbox1">
            <option value="none" hidden selected>Default</option>
            <option value="{% for product in product %}?ATOZ={{product.id}}{% endfor %}"> Name, A to Z </option>
            <option value="aye"><a href="">Name, Z to A</a></option>
            <option value="aye"><a href="">Price - Low To High</a></option>
            <option value="aye"><a href="">Price - High To Low</a></option>
            <option value="aye"><a href="">Sort By new</a></option>
            <option value="aye"><a href="">Sort By old</a></option>
        </select> {% endcomment %}
    </div>
</div>
   
  <div class="row mb-3">          
        <div class="col-lg-9 order-lg-last col-md-12 order-md-first">
            {% if messages %}
          <div class="alert alert-primary"role="alert">            
            {% for i in messages %}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{i}}
            {% endfor %}
          </div>
          {% endif %}       
            <div class="shop-bottom-area">
                <div class="row">
                    {% csrf_token %}
                    {% for product in product %}
                    <div class="col-md-5 col-lg-5 col-xl-4 mb-lm-30px mb-5">
                        <div class="product">
                            <div class="thumb">
                                <a href="javascript:void(0);" class="image">
                                    <img src="{{product.image.url}}" alt="Product" id="product-img">
                                    <img class="hover-image" src="{{product.image.url}}" alt="Product">
                                </a>
                                <span class="badges">
                                <span class="new" id="product-condition">{{ product.condition }}</span>
                                </span>                    
                                <form>
                                    {% csrf_token %}            
                                    <div class="text-center">
                                        {% if product.pk in w2 %}
                                           <button type="submit" class="fa fa-heart text-right SubmitWishlist" onclick="SubmitWishlist(this)" id="{{product.pk}}"></button>                                                                               
                                        {% else %}
                                           <button type="submit" class="fa fa-heart-o text-right SubmitWishlist" onclick="SubmitWishlist(this)" id="{{product.pk}}"></button>                                                                               
                                        {% endif %}
                                    </div> 
                                </form>                               
                            </div>
                        </div> 
                    </div>

                    <div class="col-md-7 col-lg-7 col-xl-8 mb-5">
                        <div class="content-desc-wrap">
                            <div class="content">
                                <span class="category" id="product-categories">{{ product.categories }}</span>
                                <h5 class="title text-dark" id="product-name">{{ product.name }}</h5>                                
                            </div>
                            <div class="qty-container">
                                <button class="qty-btn-minus btn-primary btn-rounded mr-1" type="button" onclick="MinusQuantity(this)"><i class="fa fa-minus"></i></button>
                                <input type="text" name="quantity" value="1" class="input-qty input-rounded">                                
                                <button class="qty-btn-plus btn-primary btn-rounded ml-1" type="button"  onclick="AddQuantity(this)"><i class="fa fa-plus"></i></button>
                                <input class="product-stock" id="{{product.total_stock}}" value="{{product.total_stock}}" hidden>
                            </div>
                            <div class="box-inner">
                                <span class="price">
                                    <span class="new" id="product-price">${{product.price}}</span>
                                </span>

                                <p id="product-description" class="mb-3">{{ product.description | safe }}</p>

                                {% comment %} <form action="{% url 'addtocart' product.pk %}" method="POST">
                                    {% endcomment %}
                                    <div>
                                        {% csrf_token %}
                                        {% comment %} {% if product.quantity >= product.total_stock %}
                                        <h4 class="text-dark">OUTOFSTOCK</h4>
                                        {% else %} {% endcomment %}
                                        {% comment %} <a href="{% url 'showmycart' %}"><button type="submit" class="AddTocart">Add To Cart</button></a> {% endcomment %}
                                        <button type="submit" class="AddTocart mt-3" id="{{product.pk}}" onclick="SaveAddToCart(this)">Add To Cart</button>
                                        <a href="{% url 'checkout' %}"><button class="ButNow mt-2 bg-dark">Buy Now</button></a>
                                        {% comment %} {% endif %} {% endcomment %}
                                    </div>
                                    {% comment %}
                                </form> {% endcomment %}
                            </div>
                        </div>
                    </div>
                    <img src="{{product.image.urls}}" />
                    {% endfor %}                                                            
                                                        
                </div>
            </div> 
        </div>    
        <div class="col-lg-3 order-lg-first col-md-12 order-md-last">
            <div class="shop-sidebar-wrap">
                <!-- Sidebar single item -->
                <div class="sidebar-widget">
                    <h4 class="sidebar-title">Top Categories</h4>
                    {% comment %} {% for cat in categories %}                    
                    <div class="sidebar-widget-category">                                                                        
                        <ul class="nav nav-stacked" id="accordion1-{{forloop.counter}}">                            
                            <li class="panel"> <a data-toggle="collapse" data-parent="#accordion1-{{forloop.counter}}" href="#firstLink">{{cat.name}}</a>                              
                                <ul id="firstLink" class="collapse">  
                                    {%for i in cat.subcategories_set.all%}                                                              
                                    <li>{{i.name}}</li>
                                    {% endfor %}
                                </ul>
                            </li>                                                       
                        </ul>
                    </div>
                    {% endfor %}  {% endcomment %}
                    {% comment %} {% endfor %} {% endcomment %}                    
                    <div class="accordion">
                        <ul>
                            <li class="pagenav">
                              <h4><a href="/product/">All Category</a></h4>
                            </li>
                        </ul>  
                        {% for cat in categories %}                      
                        <ul>
                          <li class="pagenav">
                            <h4><a href="javascript:void(0)">{{cat.name}}</a><i class="fa fa-angle-right"></i></h4>                            
                            <ul>                                
                            {%for i in cat.subcategories_set.all%}
                              <li class="page_item"><a href="/product/?subcategory={{i.id}}" class="active={{i.id}}">{{i.name}}</a></li>
                            {% endfor %}                              
                            </ul>                            
                          </li>
                        </ul> 
                        {% endfor %}                                                                                               
                    </div>                    
                </div>
                <!-- Sidebar single item -->
                <div class="sidebar-widget mt-8">
                    <h4 class="sidebar-title">Filter</h4>
                    <div class="sidebar-widget-category">
                        {% for i in filter_price %}                        
                        <ul class="d-flex flex-wrap">                                                        
                            <li><a href="/product/?filter_price={{i.id}}" class="">{{i.price}}</a></li>                                                                                                               
                        </ul>
                        {% endfor %}                        
                    </div>                    
                </div>                
            </div>
        </div>        
  </div>  
{% endblock %}

{% block javascript %}
<script src="{% static 'js/Master/product.js' %}"></script>
{% endblock %}